version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      # - MYSQL_DATABASE=nodedb
      # - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: nginx
  #   restart: always
  #   networks:
  #     - app-network
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app

  # app:
  #   build:
  #     context: ./node
  #   container_name: app
  #   entrypoint: sh -c "npm install && node index.js"
  #   restart: always
  #   tty: true
  #   networks:
  #     - app-network
  #   volumes: 
  #     - ./node:/usr/src/app
  #     # - node_modules:/usr/src/app/node_modules      
  #   depends_on:
  #     db:
  #       condition: service_healthy

networks:
  app-network:
    driver: bridge